### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by odidev** [plone/plone.docker#103]
Issue created to enable official support of ARM64 architecture for Plone Docker.

**PR is raised as #102** 
This resolves following issue while compiling it for ARM64 architecture:
```
The headers or library files could not be found for zlib,
a required dependency when compiling Pillow from source.

Please see the install instructions at:
   https://pillow.readthedocs.io/en/latest/installation.html

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 2312, in main
    **kw
  File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 412, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 654, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 699, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 884, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1152, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1138, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/local/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 370, in _handle_tasks
    debug('task handler got sentinel')
TypeError: 'NoneType' object is not callable
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 332, in _handle_workers
    debug('worker handler exiting')
TypeError: 'NoneType' object is not callable
```

Please have a look and let me know how can i get this change merged by official community to enhance plone official docker for ARM64.

Regards,

**Comment by lag-linaro** [comment]
@avoinea I'm not sure this is an enhancement, since [Docker's Official Images build of Plone](https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/plone/) is broken and has been for some time.

[Plone on Docker Hub](https://hub.docker.com/_/plone) also indicates that it should be supported on ARM64v8.

Please could you guys work with @odidev to rectify this.  He seems keen to help fix it.

**Comment by odidev** [comment]
@lag-linaro : Thanks for support :smile: 
Plone works very well just by adding ```build-essential``` to list of dependencies.

I have verified the working and can provide logs too.

**Comment by avoinea** [comment]
Fixed by #102

**Comment by ljkenny** [comment]
It makes sense to keep this Issue open until https://github.com/docker-library/official-images/pull/4746 is merged.

(Docker's Official Images build of Plone)[https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/plone/] is still broken.

**Comment by lag-linaro** [comment]
IMHO, it makes sense to keep this Issue open until https://github.com/docker-library/official-images/pull/4746 is merged.

[Docker's Official Images build of Plone](https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/plone/) is still broken.

**Comment by avoinea** [comment]
Seems to be ok now, except [arm32v6](https://doi-janky.infosiftr.net/job/multiarch/job/arm32v6/job/plone/97/console), which seems to be a temporary connection issue:

```
Connecting to launchpad.net (91.189.89.222:443)
wget: error getting response: Connection reset by peer
```

Thank you @odidev, @lag-linaro, @tianon, @svx

**Comment by avoinea** [comment]
@lag-linaro

I don't get it, it says `UNSTABLE`, not `FAILED`:

```
The following tags failed to build:

  - plone:5.1.2-alpine
  - plone:4.3.17-alpine


The following tags built successfully:

  - plone:5.1.2
  - plone:4.3.17
```

I don't think the `alpine` tags are supposed to work on ARM64 architecture

**Comment by avoinea** [comment]
> I don't think the alpine tags are supposed to work on ARM64 architecture

Hmm, they are :)

https://github.com/docker-library/official-images/blob/5c995573aa2899a502705cd8c81b06ad624c6725/library/plone#L11

But we did nothing about it in: https://github.com/plone/plone.docker/pull/104

**Comment by lag-linaro** [comment]
I find debugging these builds is easier if the RUN commands start with 'set -x'.

Okay, so I guess that's half good. :smiley: 

What are we going to do about the broken Alpine images?
